### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by rebp** [Hsnzync/Monster-shooter#2]
# Peer review

## Polymorfisme
In de Game object zie ik dat je alle gameobjecten in 1 array pusht. Dit is een goede toepassing van polymorfisme

## Singleton
Je hebt dit patroon goed in de Game class toegepast

## Strategy
Je hebt dit patroon goed toegepast in de vorm van een fast- en slowbehavior voor de enemies.

## Observer
Dit patroon is nog niet geimplementeerd.

## Conclusie
Het spel zit er goed uit en de visuals zijn ook goed. Qua OOP heb je de meeste punten al. Je mist nog 1 polymorfisme toepassing en de observer pattern om een voldoende te halen. Success!

**Comment by Hsnzync** [comment]
Thanks maat
